# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v11
    
    - name: Install dependencies from vcpkg.json
      run: vcpkg install

    - name: Build with MSBuild
      run: |
        msbuild PandaDLL.sln /m /p:Configuration=Release /p:Platform=x64 `
          /p:AdditionalIncludeDirectories="${{ github.workspace }}\\vcpkg\\installed\\x64-windows\\include" `
          /p:AdditionalLibraryDirectories="${{ github.workspace }}\\vcpkg\\installed\\x64-windows\\lib"
